apiVersion: funk.knative.dev/v1alpha1
kind: SDKInit
metadata:
  name: funk-java-sdk
spec:
  steps:
    - name: "Creating funk directory"
      mkdir: "src/main/java/com/example/funks"
    - name: "Create funk file"
      template:
        source: "templates/funk/funk.java.tmpl"
        dest: "src/main/java/com/example/funks/{{.FunkName}}.java"
    - name: "Create service yaml"
      template:
        source: "templates/funk/service.yaml"
        dest: "config/{{.LowerFunkName}}_service.yaml"
    - name: "Create trigger yaml"
      template:
        source: "templates/funk/trigger.yaml"
        dest: "config/{{.LowerFunkName}}_trigger.yaml"
