apiVersion: funk.knative.dev/v1alpha1
kind: Type
metadata:
  name: funk-go-sdk
spec:
  template:
    source: "templates/type/type.java.tmpl"
    dest: "src/main/java/{{.Path}}/{{.UpCaseTypeName}}.java"
